### ISSUE TITLE
Multiple eventsObserver outputs in one HTML document causes z-height and other issues

### ISSUE THREAD

**Issue by charliejhadley** [ox-it/eventsObserveR#16]
The following yields a shiny app where the second tab does NOT contain the eventsObserveR ring and in the first tab there are z-height issues:

```r
library(shiny)
library(eventsObserveR)

shinyApp(
  ui = navbarPage(
    "eventsObserver",
    tabPanel(
      "one",
      eventsObserverOutput("one")
    ),
    tabPanel(
      "two",
      eventsObserverOutput("two")
    )
  ),
  server = function(input, output){
    
    output$one <- renderEventsObserver({
      eventsObserveR(events = sample_events_data,
                     place.key = "station")
    })
    
    output$two <- renderEventsObserver({
      eventsObserveR(events = sample_events_data,
                     place.key = "station")
    })
    
  }
```

![image](https://cloud.githubusercontent.com/assets/9363263/21644123/df23cf44-d283-11e6-84ac-28bf91b9d21d.png)

![image](https://cloud.githubusercontent.com/assets/9363263/21644128/e45bec76-d283-11e6-93b4-bdfc53f43119.png)

**Comment by ToonTalk** [comment]
It will be easier for me to investigate if there is a URL that reproduces the problem.

**Comment by charliejhadley** [comment]
@ToonTalk here's a simpler example using RMarkdown http://rpubs.com/martinjhnhadley/twoEventsObservers

**Comment by ToonTalk** [comment]
Thanks. Investigating...

The console shows many errors that probably are a separate issue:

> about:blank:1 Mixed Content: The page at 'https://pippio.com/api/sync?pid=1391&ref=http%3A%2F%2Frpubs.com%2Fmartinjhnhadley%2FtwoEventsObservers' was loaded over HTTPS, but requested an insecure resource 'http://lore.circulate.com/rysc?fid=lrttum'. This request has been blocked; the content must be served over HTTPS.
> lounge.bundle.c61407ceda8875555b41f987a6a45ee1.js:3 WebSocket connection to 'wss://realtime.services.disqus.com/ws/2/thread/5437810348?' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
> open @ lounge.bundle.c61407ceda8875555b41f987a6a45ee1.js:3

**Comment by ToonTalk** [comment]
When I made a quick test the second event observer instance drew the locations upside down. Probably an artefact of the way I did the testing but double check this.

**Comment by ToonTalk** [comment]
Did you get a chance to confirm that this fix worked for your examples?

**Comment by charliejhadley** [comment]
@ToonTalk this does work a treat now - many thanks!
