### ISSUE TITLE
Add support for local background.image

### ISSUE THREAD

**Issue by charliejhadley** [ox-it/eventsObserveR#17]
This requires the htmlwidget to include the image, currently don't know how to do this.

Until this is fixed there's a hammer like warning if a background.image is supplied and `RCurl::url.exists(img)` fails.

This doesn't work:

```r
eventsObserveR(
 events = sample_events_data,
 place.key = "station",
 background.image = "test-background.png"
)
```

but this does

```r
eventsObserveR(
 events = sample_events_data,
 place.key = "station",
 background.image = "https://raw.githubusercontent.com/ox-it/eventsObserveR/5ad38998f03c48dd141eab2b5188f26668347dab/test-background.png"
)
```

**Comment by ToonTalk** [comment]
I added URL background image support just before leaving Oxford. See line 47 of https://github.com/ox-it/eventsObserveR/blob/master/inst/htmlwidgets/lib/events_observer.js

A relative URL should work fine to refer to a local file.

**Comment by charliejhadley** [comment]
@toontalk thanks for reply here - I realise we're out of sync on email, will catch up thoroughly at week's end.

This would work with relative URLs if I could figure out the incantation to get htmlwidgets to suck up the image into its gubbins - which at present it doesn't. Feel the issue is on the R side, I'm going to reach out to an acquaintance about this

This doesn't work:

```r
eventsObserveR(
 events = sample_events_data,
 place.key = "station",
 background.image = "test-background.png"
)
```

but this does

```r
eventsObserveR(
 events = sample_events_data,
 place.key = "station",
 background.image = "https://raw.githubusercontent.com/ox-it/eventsObserveR/5ad38998f03c48dd141eab2b5188f26668347dab/test-background.png"
)
```

**Comment by timelyportfolio** [comment]
Based on my experience I see two options but strongly favor the first.

1. Convert the image to `base64` for both local and non-local images.  I would think this works best if there is a helper function in `eventsObserveR` for this (probably leveraging `base64enc::dataURI` or something similar), so the user simply needs to supply an image URL.

2. Make the image a dependency and attach the dependency to the `htmlwidget`.

### Option 1: convert to base64

For now, I will just demonstrate this method.  If I get time, I will try to write a short demo of option 2 for comparison.

```
# one option would be to use base64 encoded url for local images
#  this requires removal of the check for url exists
#  we will hack around it later for now

b64img <- base64enc::dataURI(
  # note: this works with local also
  # note: dataURI also works with RAW content so pairs nicely with magick
  file = "https://raw.githubusercontent.com/ox-it/eventsObserveR/5ad38998f03c48dd141eab2b5188f26668347dab/test-background.png",
  mime = "image/png"
)

# to bypass the url exists check we can hack it this way

eo <- eventsObserveR(
  events = sample_events_data,
  place.key = "station"
)

eo$x$settings$background_image <- b64img

eo
```

**Comment by charliejhadley** [comment]
Thanks @timelyportfolio base64 is a nice fix for this.
